"""empty message

Revision ID: 2094d3c32c79
Revises: 
Create Date: 2022-08-31 15:59:19.827513

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2094d3c32c79'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('provider',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('email', sa.String(length=120), nullable=False),
    sa.Column('password', sa.String(length=80), nullable=False),
    sa.Column('service', sa.String(length=80), nullable=False),
    sa.Column('terms', sa.Boolean(), nullable=False),
    sa.Column('provider_charges', sa.String(length=80), nullable=False),
    sa.Column('service_description', sa.String(length=500), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('email', sa.String(length=120), nullable=False),
    sa.Column('password', sa.String(length=80), nullable=False),
    sa.Column('terms', sa.Boolean(), nullable=False),
    sa.Column('client', sa.Boolean(), nullable=False),
    sa.Column('provider', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('evento',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('contador', sa.Integer(), nullable=True),
    sa.Column('precio_orden', sa.Float(), nullable=True),
    sa.Column('precio_total_orden', sa.Float(), nullable=True),
    sa.Column('status_orden_recibida', sa.Boolean(), nullable=True),
    sa.Column('status_orden_cancelada', sa.Boolean(), nullable=True),
    sa.Column('status_orden_aceptada', sa.Boolean(), nullable=True),
    sa.Column('status_orden_progreso', sa.Boolean(), nullable=True),
    sa.Column('status_orden_finalizada', sa.Boolean(), nullable=True),
    sa.Column('servicio', sa.String(length=250), nullable=True),
    sa.Column('cliente_id', sa.Integer(), nullable=True),
    sa.Column('proveedor_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['cliente_id'], ['user.id'], ),
    sa.ForeignKeyConstraint(['proveedor_id'], ['provider.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('evento')
    op.drop_table('user')
    op.drop_table('provider')
    # ### end Alembic commands ###
