"""empty message

Revision ID: 53eb2518de94
Revises: 
Create Date: 2022-09-01 01:48:30.252359

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '53eb2518de94'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('provider',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('email', sa.String(length=120), nullable=False),
    sa.Column('password', sa.String(length=80), nullable=False),
    sa.Column('service', sa.String(length=80), nullable=False),
    sa.Column('terms', sa.Boolean(), nullable=False),
    sa.Column('provider_charges', sa.String(length=80), nullable=False),
    sa.Column('service_description', sa.String(length=500), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('email', sa.String(length=120), nullable=False),
    sa.Column('password', sa.String(length=80), nullable=False),
    sa.Column('terms', sa.Boolean(), nullable=False),
    sa.Column('client', sa.Boolean(), nullable=False),
    sa.Column('provider', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('evento',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('contador', sa.Integer(), nullable=True),
    sa.Column('precio_orden', sa.Float(), nullable=True),
    sa.Column('precio_total_orden', sa.Float(), nullable=True),
    sa.Column('status_orden_recibida', sa.Boolean(), nullable=True),
    sa.Column('status_orden_cancelada', sa.Boolean(), nullable=True),
    sa.Column('status_orden_aceptada', sa.Boolean(), nullable=True),
    sa.Column('status_orden_progreso', sa.Boolean(), nullable=True),
    sa.Column('status_orden_finalizada', sa.Boolean(), nullable=True),
    sa.Column('servicio', sa.String(length=250), nullable=True),
    sa.Column('cliente_id', sa.Integer(), nullable=True),
    sa.Column('proveedor_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['cliente_id'], ['user.id'], ),
    sa.ForeignKeyConstraint(['proveedor_id'], ['provider.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('provider_images',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('provider_id', sa.Integer(), nullable=False),
    sa.Column('photo_url', sa.String(length=2500), nullable=False),
    sa.ForeignKeyConstraint(['provider_id'], ['provider.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('provider_images')
    op.drop_table('evento')
    op.drop_table('user')
    op.drop_table('provider')
    # ### end Alembic commands ###
