"""empty message

<<<<<<<< HEAD:migrations/versions/38b80110f6c1_.py
Revision ID: 38b80110f6c1
Revises: 
Create Date: 2022-08-29 22:24:37.884051
========
Revision ID: 9d9c97b83a9c
Revises: 
Create Date: 2022-08-30 01:11:21.992527
>>>>>>>> 4a42500d13efb030c9ca1220a4487cb0f69f896f:migrations/versions/9d9c97b83a9c_.py

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
<<<<<<<< HEAD:migrations/versions/38b80110f6c1_.py
revision = '38b80110f6c1'
========
revision = '9d9c97b83a9c'
>>>>>>>> 4a42500d13efb030c9ca1220a4487cb0f69f896f:migrations/versions/9d9c97b83a9c_.py
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('event',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('provider',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('email', sa.String(length=120), nullable=False),
    sa.Column('password', sa.String(length=80), nullable=False),
    sa.Column('service', sa.String(length=80), nullable=False),
    sa.Column('terms', sa.Boolean(), nullable=False),
    sa.Column('provider_charges', sa.String(length=80), nullable=False),
    sa.Column('service_description', sa.String(length=500), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('email', sa.String(length=120), nullable=False),
    sa.Column('password', sa.String(length=80), nullable=False),
    sa.Column('terms', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user')
    op.drop_table('provider')
    op.drop_table('event')
    # ### end Alembic commands ###
